### ISSUE TITLE
Centos 7??

### ISSUE THREAD

**Issue by wesyah234** [hellstad/meteor-please#4]
Does this tool REQUIRE centos 7+ or will it work with version 6?

**Comment by kevincharm** [comment]
Yes. It requires systemd which came in at CentOS 7. CentOS 6 and below use sysvinit so it's not compatible. You can hack it to work with sysvinit though, you just gotta make the scripts/config files for it.

**Comment by wesyah234** [comment]
Thanks for the reply... for now I'm trying to deploy manually.... I happened to come across your gist:
https://gist.github.com/hellstad/9c0a83d58d06816d266d
Is this something you created before creating meteor-please?

Also, another question, I see in your gist that you used pm2, so I looked into this tool, and I see it has a deployment feature:
http://pm2.keymetrics.io/docs/usage/deployment/

Is this similar to what you are doing with meteor-please, (and the original mup as well)?

**Comment by kevincharm** [comment]
Yes that was created long ago. It's not very practical though because you need to run it from the server. So you have to use another tool to invoke it, or ssh into the box first, then you gotta set up pm2 sysvinit service, install mongo, etc. I've never used the PM2 deployment feature, but just remember you probably have to rebuild the fibers package if your dev env is different to your prod env (e.g. OS X to x64 Linux).

If you want to deploy manually, then take a look at this repo's /scripts/ dir. You will use mostly the same steps on CentOS 6 except for all the systemd stuff.

**Comment by wesyah234** [comment]
Thanks for the explanations!
